"""Multi-tensor stochastic optimizer distillation framework."""

from optdistil.multitensor.features import (
    MULTITENSOR_FEATURE_NAMES,
    build_multitensor_features,
    concatenate_features,
)
from optdistil.multitensor.params import ParamCollection
from optdistil.multitensor.stochastic import (
    MultiTensorCase,
    artifact_metadata,
    batch_sequence,
    batch_transfer_matrix,
    collect_records,
    evaluate_student_split,
    evaluate_teacher_split,
    flatten_split,
    make_split,
    paired_differences,
    rollout_student,
    rollout_teacher,
    select_outer_lr_and_train,
    select_student_scale,
    summarize_ratios,
    train_closed_loop_meta,
    train_direct_meta_student,
    train_supervised_student,
    tune_teacher_lr,
    width_transfer_matrix,
)
from optdistil.multitensor.tasks import (
    ResidualMLPRegressionTask,
    TwoLayerMLPRegressionTask,
    make_residual_mlp,
    make_task,
    make_two_layer_mlp,
)
from optdistil.multitensor.teachers import (
    TEACHER_METHODS,
    AdamWMultiTensor,
    LBFGSMultiTensor,
    MomentumSGDMultiTensor,
    MuonHybridTeacher,
    NormGradGlobal,
    NormGradTensorWise,
    SGDMultiTensor,
    make_teacher,
)

__all__ = [
    "MULTITENSOR_FEATURE_NAMES",
    "TEACHER_METHODS",
    "AdamWMultiTensor",
    "LBFGSMultiTensor",
    "MomentumSGDMultiTensor",
    "MultiTensorCase",
    "MuonHybridTeacher",
    "NormGradGlobal",
    "NormGradTensorWise",
    "ParamCollection",
    "ResidualMLPRegressionTask",
    "SGDMultiTensor",
    "TwoLayerMLPRegressionTask",
    "artifact_metadata",
    "batch_sequence",
    "batch_transfer_matrix",
    "build_multitensor_features",
    "collect_records",
    "concatenate_features",
    "evaluate_student_split",
    "evaluate_teacher_split",
    "flatten_split",
    "make_residual_mlp",
    "make_split",
    "make_task",
    "make_teacher",
    "make_two_layer_mlp",
    "paired_differences",
    "rollout_student",
    "rollout_teacher",
    "select_outer_lr_and_train",
    "select_student_scale",
    "summarize_ratios",
    "train_closed_loop_meta",
    "train_direct_meta_student",
    "train_supervised_student",
    "tune_teacher_lr",
    "width_transfer_matrix",
]
